### ISSUE TITLE
Queue clearQueue() parameter not implemented?

### ISSUE THREAD

**Issue by zhaobenny** [Projects-Me/LavaJS#12]
![Image](https://user-images.githubusercontent.com/46238123/87862515-dabc1480-c905-11ea-82ea-74400506e0d2.PNG)

Using the parameter doesn't do anything.
Was this a mistake in documentation and is not going to get implemented?

**Comment by ThatAnonyG** [comment]
It should clear the queue in theory. I will mark this as a bug for now. Please use `queue.clear()` for the time being.

**Comment by zhaobenny** [comment]
> It should clear the queue in theory. I will mark this as a bug for now. Please use `queue.clear()` for the time being.

It does clear the queue. but using the start parameter doesn't seem to do anything.

**Comment by ThatAnonyG** [comment]
> > It should clear the queue in theory. I will mark this as a bug for now. Please use `queue.clear()` for the time being.
> 
> It does clear the queue. but using the start parameter doesn't seem to do anything.

Ahh I see now. Yea the start parameter is deprecated in the latest version. I will update the docs right away. For removing a single track use [`Queue.remove()`](https://lavajs.tech/#/docs/Queue?id=removeposition) and for removing multiple ones use [`Queue.wipe()`](https://lavajs.tech/#/docs/Queue?id=wipestart-end). I will mark is Invalid and close it. Thanks for bringing this to my notice.
