### ISSUE TITLE
Feature Request: Please make LavaJS supportable for Eris

### ISSUE THREAD

**Issue by thrace19** [Projects-Me/LavaJS#15]

**Comment by ThatAnonyG** [comment]
Currently we only support DiscordJS so not yet. We plan on making it dynamic enough to support all libraries. If you want then you can edit the question to make this a feature request. Till then I will keep this thread open. Have a nice day!

**Comment by ThatAnonyG** [comment]
Thanks for you time! We will work this and release an update as soon as possible. Till then, happy coding!

**Comment by ThatAnonyG** [comment]
@inhydrox Update on the request: LavaJS team is actively working on bringing out the new v4 with extended support for Eris. We are extremely sorry for the delay but turns out we had to start work on the library from absolutely ground up. Please wait a bit more and we will release it very very soon!

**Comment by thrace19** [comment]
No problem

**Comment by ThatAnonyG** [comment]
Hello, I'd like you to inform you that I launched a new Lavalink wrapper called [Playlink](https://github.com/OverleapCo/Playlink) which supports all discord libraries and has an allover better design than LavaJS. Please consider using that for Eris! On this note I will be closing this issue!
