### ISSUE TITLE
Player doesnt reconnect after track stuck

### ISSUE THREAD

**Issue by mananchawla2005** [Projects-Me/LavaJS#18]
Actually when the player is manually disconnected, it doesnt reconnect by itself when play command is executed again after some time. And i made sure skip on error is set to true.
Expected- It should stop the player clear the queue on manually disconnect and then start over new queue when joined the channel again.

**Comment by ThatAnonymousG** [comment]
@mananchawla2005 Can you show me how you are handling the trackStuck event?

**Comment by ThatAnonyG** [comment]
@mananchawla2005 Can you show me how you are handling the `trackStuck` event?

**Comment by ThatAnonyG** [comment]
@mananchawla2005 Marking as Invalid due to a lack of information. Please open it again when you can provide an answer to the above question.
