### ISSUE TITLE
The add option on player lavaSearch is inverted

### ISSUE THREAD

**Issue by Giova978** [Projects-Me/LavaJS#19]
When you pass `{ add: true }` the method will not add the song automatically to the queue but if you pass `{ add: false }` it will. I believe this is contra intuitive and should be the other way around

**Comment by ThatAnonyG** [comment]
Oh, thanks for the report! Should be fixed in the next update.

**Comment by Giova978** [comment]
Your welcome and thank you for the awesome job with this package
