### ISSUE TITLE
broke my packages

### ISSUE THREAD

**Issue by d-513** [Projects-Me/LavaJS#23]
It seems that LavaJS was removed from NPM causing my bot to break. I know this is not maintained but please do not use such compatibility breaking techniques as porting over to a new lib takes time

**Comment by d-513** [comment]
Playlink 404's too. What happened? https://github.com/OverleapCo/Playlink/

**Comment by ThatAnonyG** [comment]
> It seems that LavaJS was removed from NPM causing my bot to break. I know this is not maintained but please do not use such compatibility breaking techniques as porting over to a new lib takes time

I am extremely sorry for the inconvinience caused. My NPM account itself was deleted which is why all my packages were removed too. And Playlink has been archived as I am finding myself too caught up to work on these projects. Again very sorry for what happened.
