### ISSUE TITLE
Not in the NPM repository anymore

### ISSUE THREAD

**Issue by GoudronViande24** [Projects-Me/LavaJS#24]
Hi, I can't install LavaJS, npm tells me this:

```bash
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@anonymousg%2flavajs - Not found
npm ERR! 404
npm ERR! 404  '@anonymousg/lavajs@^3.5.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by ThatAnonyG** [comment]
Hello! Sorry, this project is no more maintained, and it got removed from NPM a while back. We are working on a new and improved version of LavaJS. Till then you can clone this repository and use it locally within your project.
