### ISSUE TITLE
[Suggestion] Add a function equalizer in Player

### ISSUE THREAD

**Issue by MeatReed** [Projects-Me/LavaJS#6]
You can add a function equalizer in Player please?
```js
Player.equalizer(band, gain);
```

**Comment by ThatAnonyG** [comment]
> You can add a function equalizer in Player please ?
> ```js
> Player.equalizer(band, gain);
> ```

Thanks for taking your time. We will add equaliser. Expect it to be added and released in version 3.0. Happy coding!

**Comment by ThatAnonyG** [comment]
@MeatReed We said it will be released in v3.0.0 but when changing some stuff we realised the need of some more features. So there is a high chance that they will come bundled together in v3.1.0.

**Comment by ThatAnonyG** [comment]
As promised. The new features have been added in version 3.1.0. Enjoy!
